# Generated by Django 6.0.6 on 2026-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
